# Generated by Django 3.2.9 on 2021-12-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_answer_marks_of_user_multiplechoicequestion_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='descrption',
            new_name='description',
        ),
    ]
