# Generated by Django 3.2.9 on 2022-03-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fee_fee_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='year',
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
