# Generated by Django 3.2.9 on 2022-03-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220318_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.IntegerField()),
                ('quiz', models.IntegerField()),
                ('homework', models.IntegerField()),
                ('project', models.IntegerField()),
                ('test', models.IntegerField()),
            ],
        ),
    ]
