# Generated by Django 3.2.9 on 2021-12-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211228_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
