# Generated by Django 3.2.9 on 2022-03-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_gradeweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='users.gradeweight'),
        ),
    ]
