# Generated by Django 3.2.9 on 2021-12-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
