# Generated by Django 3.2.5 on 2021-07-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210721_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
