# Generated by Django 3.2.9 on 2022-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_course_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='point_grade',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
