# Generated by Django 3.2.9 on 2022-03-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_grade_point_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
