# Generated by Django 3.2.5 on 2021-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210721_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', height_field='100px', upload_to='profile_pics', width_field='100px'),
        ),
    ]
