# Generated by Django 3.2.9 on 2022-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_course_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, null=True)),
                ('courses', models.ManyToManyField(to='users.Course')),
            ],
        ),
    ]
