# Generated by Django 3.2.9 on 2021-12-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211231_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='AssignmentFile',
        ),
    ]
