# Generated by Django 3.2.9 on 2022-01-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211231_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='note',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_now',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(auto_now=True)),
                ('note', models.TextField(max_length=500, null=True)),
                ('is_absent', models.BooleanField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendace_reports',
            field=models.ManyToManyField(to='users.AttendanceReport'),
        ),
    ]
