# Generated by Django 3.2.9 on 2022-03-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_semester_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
