# Generated by Django 3.2.9 on 2021-11-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
