# Generated by Django 3.2.9 on 2022-01-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_attendancereport_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='file',
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='note',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='documents/%Y/%m/%d')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submission_files', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateField()),
                ('description', models.CharField(max_length=9000)),
                ('files', models.ManyToManyField(to='users.AssignmentSubmissionFiles')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.grade')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submission', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='documents/%Y/%m/%d')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_submission_files', to='users.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='files',
            field=models.ManyToManyField(to='users.AssignmentFile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_submissions',
            field=models.ManyToManyField(to='users.AssignmentSubmission'),
        ),
    ]
