# Generated by Django 3.2.9 on 2022-03-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_semester_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
