# Generated by Django 3.2.9 on 2022-03-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_semester_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='archive',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
