# Generated by Django 3.2.9 on 2021-11-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STU', 'Student'), ('STA', 'Staff'), ('ADM', 'Admin')], default='STU', max_length=8),
        ),
    ]
