# Generated by Django 3.2.9 on 2022-03-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220325_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
