# Generated by Django 3.2.9 on 2022-03-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_semester_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='archive',
        ),
    ]
