# Generated by Django 3.2.9 on 2022-02-01 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_assignmentsubmission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_submission', to='users.course'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
