# Generated by Django 3.2.9 on 2022-03-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_course_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='students',
            field=models.ManyToManyField(to='users.CustomUser'),
        ),
    ]
