# Generated by Django 3.2.9 on 2022-02-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220201_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='grade',
        ),
    ]
