# Generated by Django 3.2.9 on 2022-03-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_semester_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='staff',
            field=models.ManyToManyField(related_name='semester_staff', to='users.CustomUser'),
        ),
    ]
