# Generated by Django 3.2.9 on 2022-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_semester_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(related_name='course_assignments', to='users.Assignment'),
        ),
    ]
