# Generated by Django 3.2.9 on 2021-11-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_attendance_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='docfile',
            field=models.FileField(upload_to='documents'),
        ),
    ]
