# Generated by Django 3.2.9 on 2022-02-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recievers',
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='users.customuser'),
        ),
    ]
