# Generated by Django 3.2.9 on 2021-11-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_post_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
    ]
