# Generated by Django 3.2.9 on 2022-02-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220205_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='date_reply',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(to='users.MailFiles'),
        ),
        migrations.AddField(
            model_name='reply',
            name='files',
            field=models.ManyToManyField(to='users.MailFiles'),
        ),
    ]
