# Generated by Django 3.2.9 on 2022-02-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220205_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(to='users.Reply'),
        ),
    ]
