# Generated by Django 3.2.9 on 2021-12-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grade', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('B-', 'B-'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], default='A', max_length=50)),
                ('point_grade', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=9000)),
                ('due_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('Test', 'Test'), ('Quiz', 'Quiz'), ('Homework', 'Homework'), ('Project', 'Project'), ('Task', 'Task')], default='Task', max_length=50)),
                ('possible_points', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='users.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
                ('students_grades', models.ManyToManyField(related_name='grades', to='users.CustomUser')),
            ],
        ),
    ]
