# Generated by Django 3.2.9 on 2022-02-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20220206_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='possible_points',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='FeeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_full', models.BooleanField()),
                ('note', models.CharField(max_length=255)),
                ('amount_paid', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('UNKOWN', 'Unknown')], default='UNKOWN', max_length=10)),
                ('paid_full', models.BooleanField()),
                ('note', models.CharField(max_length=255)),
                ('amount_paid', models.IntegerField()),
                ('student_fees', models.ManyToManyField(to='users.FeeReport')),
            ],
        ),
    ]
